version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout

      - run:
          name: Update NPM
          command: "sudo npm install -g yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: yarn build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  version: 2
  setup_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
